# --- General Settings ---
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:Tc" # Enable TrueColor (matches termguicolors in Vim)
set -g mouse on #clickable terminal

# Start counting at 1 for both windows and panes
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

#list other sessions
bind s choose-tree 

# Split vertically with |
bind | split-window -h -c "#{pane_current_path}"

# Split horizontally with _
bind _ split-window -v -c "#{pane_current_path}"

# Use Vi keys in copy mode
setw -g mode-keys vi

# --- Mappings ---
# Alt + Arrows to move between panes
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Alt + 1-6 to move between windows
bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5
bind -n M-6 select-window -t 6


# Alt + Shift + 1-6 to move between panes
bind -n M-! select-pane -t 1
bind -n M-@ select-pane -t 2
bind -n M-# select-pane -t 3
bind -n M-$ select-pane -t 4
bind -n M-% select-pane -t 5
bind -n M-^ select-pane -t 6

## Split windows into the current directory path
#bind '"' split-window -v -c "#{pane_current_path}"
#bind % split-window -h -c "#{pane_current_path}"

# Easy reload of tmux.conf
bind r source-file ~/.tmux.conf \; display "Reloaded!"



# Set the background of the active pane
set -g window-active-style 'fg=terminal,bg=terminal'
# Set the background of the inactive pane(s)
set -g window-style 'fg=terminal,bg=terminal'



## border style
set -g pane-border-lines heavy  # Options: single, double, heavy, simple, or padded
# Enable pane status (labels on the borders)
set -g pane-border-status top
set -g pane-border-format '#P'
set -g pane-active-border-style "fg=#793fe4"
set -g pane-border-style "fg=#505050"


#update status every 300 seconds (don't need to update but keep for later)
set -g status-interval 300


## status left (session name)
set -g status-left-style 'fg=#ffffff,bg=#793fe4,bold'
set -g status-left ' Session: #S  #[bg=#181922] ' # Adds some padding around the session name
set -g status-left-length 22


set -g status-style 'fg=#ffffff,bg=#181922,bold'
setw -g window-status-style "fg=#ffffff,bg=#959db5,bold"

# The ACTIVE window (Bold Black)
setw -g window-status-current-format "#[fg=#000000,bg=#ffb1ff,bold] #I:#W "
# The INACTIVE windows (Dimmed/Darker)
setw -g window-status-format " #I:#W "


set -g status-right-style 'fg=#000000,bg=#ef831d,bold'
#set -g status-right "  #(whoami)@#h [ %H:%M %a %d-%b-%y ] "

set -g status-right "#{?client_prefix, CMD? #(whoami)@#h [ %H:%M %a %d-%b-%y ], #(whoami)@#h [%H:%M %a %d-%b-%y]}"
set -g status-right-length 50
